### ISSUE TITLE
Utils module is missing

### ISSUE THREAD

**Issue by sairajd044** [mdhosen/Mask-Face-Inpainting-Using-Residual-Attention-Unet#2]
Is utils module that contain Configuration, DataGenerator, UNet, ResAttnUnet missing ?

**Comment by mdhosen** [comment]
Please download complete folder from here [Link](https://bit.ly/3r0NFlo).

**Comment by sairajd044** [comment]
Thank you!

**Comment by mdhosen** [comment]
Closing this issue as the problem solved.
